In [5]:
import numpy as np
import pandas as pd

data = pd.read_csv('Titanic_Cleaned.csv')
data.describe(include = "all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,SurvivalStatus
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889,891,891
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3,17,2
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",M,NaN,NaN,NaN,347082,NaN,G6,S,Mr,Not Survived
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644,517,549
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN,NaN,NaN

In [ ]:


data.corr(numeric_only = True)
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Title',
       'SurvivalStatus'],
      dtype='str')

In [9]:
data.duplicated().sum()

np.int64(0)

In [10]:
data.isnull().sum()

PassengerId         0
Survived            0
Pclass              0
Name                0
Sex                 0
Age               177
SibSp               0
Parch               0
Ticket              0
Fare                0
Cabin             687
Embarked            2
Title               0
SurvivalStatus      0
dtype: int64

In [13]:
data.iloc[10:15] # jisbi colum ka check krna chata h isko print kara ka dega like first row value row no. do print kara ka dega we can write start point and end point

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,SurvivalStatus
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",F,4.0,1,1,PP 9549,16.7000,G6,S,Miss,Survived
11,12,1,1,"Bonnell, Miss. Elizabeth",F,58.0,0,0,113783,26.5500,C103,S,Miss,Survived
12,13,0,3,"Saundercock, Mr. William Henry",M,20.0,0,0,A/5. 2151,8.0500,NaN,S,Mr,Not Survived
13,14,0,3,"Andersson, Mr. Anders Johan",M,39.0,1,5,347082,31.2750,NaN,S,Mr,Not Survived
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",F,14.0,0,0,350406,7.8542,NaN,S,Miss,Not Survived

In [14]:
data.iloc[0:5 , 0:4] # print row or column both

,PassengerId,Survived,Pclass,Name
0,1,0,3,"Braund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,3,"Heikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,5,0,3,"Allen, Mr. William Henry"

In [15]:
data['Survived']

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
data.loc[data["Age"]>50] # check age whose > 50

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,SurvivalStatus
6,7,0,1,"McCarthy, Mr. Timothy J",M,54.0,0,0,17463,51.8625,E46,S,Mr,Not Survived
11,12,1,1,"Bonnell, Miss. Elizabeth",F,58.0,0,0,113783,26.5500,C103,S,Miss,Survived
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",F,55.0,0,0,248706,16.0000,NaN,S,Mrs,Survived
33,34,0,2,"Wheadon, Mr. Edward H",M,66.0,0,0,C.A. 24579,10.5000,NaN,S,Mr,Not Survived
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",M,65.0,0,1,113509,61.9792,B30,C,Mr,Not Survived
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,821,1,1,"Hays, Mrs. Charles Melville (Clara Jennings Gr...",F,52.0,1,1,12749,93.5000,B69,S,Mrs,Survived
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",F,62.0,0,0,113572,80.0000,B28,NaN,Mrs,Survived
851,852,0,3,"Svensson, Mr. Johan",M,74.0,0,0,347060,7.7750,NaN,S,Mr,Not Survived
857,858,1,1,"Daly, Mr. Peter Denis",M,51.0,0,0,113055,26.5500,E17,S,Mr,Survived
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",F,56.0,0,1,11767,83.1583,C50,C,Mrs,Survived

In [18]:
data['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [22]:
data.loc[data["Pclass"]== 2 , ["Name" , "Age" , "Gender" , "Cabin","Survied"]]

KeyError: "['Gender', 'Survied'] not in index"